"""Ticket CRUD and status lifecycle queries."""


async def create_ticket(pool, customer_id, subject, category, source_channel,
                        priority="medium", conversation_id=None):
    """Create a support ticket. ticket_number auto-generated by DB trigger."""
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            """INSERT INTO tickets
               (ticket_number, customer_id, subject, category, source_channel, priority, conversation_id)
               VALUES ('', $1, $2, $3, $4, $5, $6)
               RETURNING *""",
            customer_id, subject, category, source_channel, priority, conversation_id,
        )
        return dict(row) if row else None


async def get_ticket_by_number(pool, ticket_number):
    """Get ticket by human-readable ticket number (TKT-XXXX)."""
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT * FROM tickets WHERE ticket_number = $1", ticket_number
        )
        return dict(row) if row else None


async def update_ticket_status(pool, ticket_id, status, escalation_reason=None,
                               resolution_notes=None):
    """Update ticket status with optional escalation/resolution info."""
    resolved_at_clause = ", resolved_at = NOW()" if status in ("resolved", "closed") else ""
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            f"""UPDATE tickets
                SET status = $2, escalation_reason = $3, resolution_notes = $4{resolved_at_clause}
                WHERE id = $1 RETURNING *""",
            ticket_id, status, escalation_reason, resolution_notes,
        )
        return dict(row) if row else None


async def get_tickets_by_customer(pool, customer_id):
    """Get all tickets for a customer."""
    async with pool.acquire() as conn:
        rows = await conn.fetch(
            """SELECT * FROM tickets
               WHERE customer_id = $1
               ORDER BY created_at DESC""",
            customer_id,
        )
        return [dict(r) for r in rows]
